apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: <NAMESPACE>

  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: terraform-k8s

data:
  primary.cnf: |
    [mysqld]

    server-id=1

    log_bin=mysql-bin

    binlog_format=ROW

    gtid_mode=ON

    enforce_gtid_consistency=ON

    log_replica_updates=ON

    binlog_expire_logs_seconds=604800

    max_connections=300

    default_authentication_plugin=mysql_native_password

  replica.cnf: |
    [mysqld]

    server-id=2

    relay_log=mysql-relay-bin

    read_only=ON

    super_read_only=ON

    gtid_mode=ON

    enforce_gtid_consistency=ON

    log_replica_updates=ON

    max_connections=300

    default_authentication_plugin=mysql_native_password
