apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: <NAMESPACE>

  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: terraform-k8s

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: "<MYSQL_ROOT_PASSWORD>"
  MYSQL_DATABASE: "<MYSQL_DATABASE>"
  MYSQL_REPLICATION_USER: "<MYSQL_REPLICATION_USER>"
  MYSQL_REPLICATION_PASSWORD: "<MYSQL_REPLICATION_PASSWORD>"
